### ISSUE TITLE
Printed url for flake does not work: Unexpected fragment

### ISSUE THREAD

**Issue by UnderTheCarpet** [jeff-hykin/nix_version_search_cli#3]
Using an URL like `spdlog.url = "https://github.com/NixOS/nixpkgs/archive/407f8825b321617a38b86a4d9be11fd76d513da2.tar.gz#spdlog"`, as suggested by `nvs` as an input of an flake results in `error: unexpected fragment 'spdlog' in flake reference 'https://github.com/NixOS/nixpkgs/archive/407f8825b321617a38b86a4d9be11fd76d513da2.tar.gz#spdlog'`.

Whereas `nix run https://github.com/NixOS/nixpkgs/archive/407f8825b321617a38b86a4d9be11fd76d513da2.tar.gz#hello` works.

**Comment by jeff-hykin** [comment]
Edit: I'm pretty inexperienced with nix flakes, and it looks like I screwed up the format. There might not be a way to have it directly as a nix flake input. However, there is a next-best workaround so I put that in `nvs` and published v1.3.3 just now

**Comment by jeff-hykin** [comment]
Also if a flake input doesn't work for some reason `nvs --repl spdlog` will show the non-flake version which still works.

**Comment by UnderTheCarpet** [comment]
The only way I know is to provide a pinned nixpkgs as a whole (without trailing `#foo`) as a flake input and work from there.

See https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake for a reference.

**Comment by jeff-hykin** [comment]
👍 Sounds good. That's the format I switched it to in v1.3.3.
